// generated by tools/voices.py from Speak/ — do not edit by hand
const VOICES = {
 "English": {
  "selected": [
   "Speak/English/selected/A_1.mp3"
  ],
  "on_the_way": [
   "Speak/English/on_the_way/A_1.mp3"
  ],
  "attacking": [
   "Speak/English/attacking/A_1.mp3"
  ],
  "holding": [
   "Speak/English/holding/A_1.mp3"
  ],
  "retreating": [
   "Speak/English/retreating/A_1.mp3"
  ],
  "in_position": [
   "Speak/English/in_position/A_1.mp3"
  ],
  "under_attack": [
   "Speak/English/under_attack/A_1.mp3",
   "Speak/English/under_attack/Sample_1.mp3"
  ],
  "heavy_losses": [
   "Speak/English/heavy_losses/A_1.mp3"
  ],
  "squad_lost": [
   "Speak/English/squad_lost/A_1.mp3"
  ],
  "friendly_fire": [
   "Speak/English/friendly_fire/A_1.mp3"
  ],
  "promoted": [
   "Speak/English/promoted/A_1.mp3"
  ],
  "say_again": [
   "Speak/English/say_again/A_1.mp3"
  ],
  "forward_hq": [
   "Speak/English/forward_hq/A_1.mp3"
  ],
  "building_lost": [
   "Speak/English/building_lost/A_1.mp3"
  ],
  "base_attack": [
   "Speak/English/base_attack/A_1.mp3"
  ],
  "fhq_attack": [
   "Speak/English/fhq_attack/A_1.mp3"
  ],
  "hq_attack": [
   "Speak/English/hq_attack/A_1.mp3"
  ],
  "drone_lost": [
   "Speak/English/drone_lost/A_1.mp3"
  ],
  "dozer_ready": [
   "Speak/English/dozer_ready/A_1.mp3"
  ],
  "dozer_idle": [
   "Speak/English/dozer_idle/A_1.mp3"
  ],
  "radio_ready": [
   "Speak/English/radio_ready/A_1.mp3"
  ],
  "fhq_ready": [
   "Speak/English/fhq_ready/A_1.mp3"
  ],
  "drone_ready": [
   "Speak/English/drone_ready/A_1.mp3"
  ],
  "place_hq": [
   "Speak/English/place_hq/A_1.mp3"
  ]
 },
 "Hebrew": {
  "selected": [
   "Speak/Hebrew/selected/A_1.mp3"
  ],
  "on_the_way": [
   "Speak/Hebrew/on_the_way/A_1.mp3"
  ],
  "attacking": [
   "Speak/Hebrew/attacking/A_1.mp3"
  ],
  "holding": [
   "Speak/Hebrew/holding/A_1.mp3"
  ],
  "retreating": [
   "Speak/Hebrew/retreating/A_1.mp3"
  ],
  "in_position": [
   "Speak/Hebrew/in_position/A_1.mp3"
  ],
  "under_attack": [
   "Speak/Hebrew/under_attack/A_1.mp3"
  ],
  "heavy_losses": [
   "Speak/Hebrew/heavy_losses/A_1.mp3"
  ],
  "squad_lost": [
   "Speak/Hebrew/squad_lost/A_1.mp3"
  ],
  "friendly_fire": [
   "Speak/Hebrew/friendly_fire/A_1.mp3"
  ],
  "promoted": [
   "Speak/Hebrew/promoted/A_1.mp3"
  ],
  "say_again": [
   "Speak/Hebrew/say_again/A_1.mp3"
  ],
  "forward_hq": [
   "Speak/Hebrew/forward_hq/A_1.mp3"
  ],
  "building_lost": [
   "Speak/Hebrew/building_lost/A_1.mp3"
  ],
  "base_attack": [
   "Speak/Hebrew/base_attack/A_1.mp3"
  ],
  "fhq_attack": [
   "Speak/Hebrew/fhq_attack/A_1.mp3"
  ],
  "hq_attack": [
   "Speak/Hebrew/hq_attack/A_1.mp3"
  ],
  "drone_lost": [
   "Speak/Hebrew/drone_lost/A_1.mp3"
  ],
  "dozer_ready": [
   "Speak/Hebrew/dozer_ready/A_1.mp3"
  ],
  "dozer_idle": [
   "Speak/Hebrew/dozer_idle/A_1.mp3"
  ],
  "radio_ready": [
   "Speak/Hebrew/radio_ready/A_1.mp3"
  ],
  "fhq_ready": [
   "Speak/Hebrew/fhq_ready/A_1.mp3"
  ],
  "drone_ready": [
   "Speak/Hebrew/drone_ready/A_1.mp3"
  ],
  "place_hq": [
   "Speak/Hebrew/place_hq/A_1.mp3"
  ]
 }
};
