# Builds js/ui/tiles.js (and notes the main menu's pictures, art/menu.jpg and art/menu_tall.jpg, if they're there) from the ground pictures in art/Background (grass1, grass2, dirt, rocky, mud): each made to
# repeat without a seam (blended with itself shifted by half, the shifted copy covering the edges), scaled down, and
# written in as a JPEG data URI.
#   python tools/tiles.py
# Needs Pillow.
import base64, io, json, os
from PIL import Image, ImageChops

ROOT = os.path.join(os.path.dirname(__file__), '..')
NAMES = ['grass1', 'grass2', 'dirt', 'rocky', 'mud']
SIZE = 512

def seamless(im):
    W, H = im.size
    shifted = ImageChops.offset(im, W // 2, H // 2)
    # the mask: 1 in the middle (the picture itself), 0 at the edges (the shifted copy, whose own seam is in its middle)
    m = Image.new('L', (W, H)); px = m.load()
    for y in range(H):
        for x in range(W):
            dx, dy = min(x, W - 1 - x) / (W / 2), min(y, H - 1 - y) / (H / 2)
            px[x, y] = int(255 * max(0.0, min(1.0, (min(dx, dy) - 0.05) / 0.35)))
    return Image.composite(im, shifted, m)

def build():
    out = {}
    for n in NAMES:
        f = next((os.path.join(ROOT, 'art', 'Background', n + e) for e in ('.jpg', '.jpeg', '.png') if os.path.exists(os.path.join(ROOT, 'art', 'Background', n + e))), None)
        if not f: continue
        im = Image.open(f).convert('RGB').resize((SIZE * 2, SIZE * 2), Image.LANCZOS)
        im = seamless(im).resize((SIZE, SIZE), Image.LANCZOS)
        b = io.BytesIO(); im.save(b, 'JPEG', quality=86)
        out[n] = 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode()
        print(n, len(b.getvalue()) // 1024, 'KB')
    js = ['// generated by tools/tiles.py from art/Background — do not edit by hand', 'const TILES = {']
    js += [f"  {n}: '{src}'," for n, src in out.items()] + ['};']
    # the main menu's pictures, if they're there (referenced by path, not built in: they're big)
    art = {}
    for key, n in (('wide', 'menu'), ('tall', 'menu_tall')):
        f = next((n + e for e in ('.jpg', '.jpeg', '.png', '.webp') if os.path.exists(os.path.join(ROOT, 'art', n + e))), None)
        art[key] = f'art/{f}' if f else None
    # (and the moving one: video/menu_loop.mp4, made from video/Menu.mp4 — slowed to half, its end faded into its
    # start — with video/menu_poster.jpg showing until it plays)
    has = lambda p: os.path.exists(os.path.join(ROOT, *p.split('/')))
    if has('video/menu_poster.jpg'): art['wide'] = art['wide'] or 'video/menu_poster.jpg'
    art['video'] = 'video/menu_loop.mp4' if has('video/menu_loop.mp4') else None
    js.append('const MENU_ART = ' + json.dumps(art) + ';')
    open(os.path.join(ROOT, 'js', 'ui', 'tiles.js'), 'w', encoding='utf-8').write('\n'.join(js) + '\n')

build()
