# Builds js/ui/tiles.js from the ground pictures in art/Background (grass1, grass2, dirt, rocky, mud): each made to
# repeat without a seam (blended with itself shifted by half, the shifted copy covering the edges), scaled down, and
# written in as a JPEG data URI.
#   python tools/tiles.py
# Needs Pillow.
import base64, io, os
from PIL import Image, ImageChops

ROOT = os.path.join(os.path.dirname(__file__), '..')
NAMES = ['grass1', 'grass2', 'dirt', 'rocky', 'mud']
SIZE = 512

def seamless(im):
    W, H = im.size
    shifted = ImageChops.offset(im, W // 2, H // 2)
    # the mask: 1 in the middle (the picture itself), 0 at the edges (the shifted copy, whose own seam is in its middle)
    m = Image.new('L', (W, H)); px = m.load()
    for y in range(H):
        for x in range(W):
            dx, dy = min(x, W - 1 - x) / (W / 2), min(y, H - 1 - y) / (H / 2)
            px[x, y] = int(255 * max(0.0, min(1.0, (min(dx, dy) - 0.05) / 0.35)))
    return Image.composite(im, shifted, m)

def build():
    out = {}
    for n in NAMES:
        f = next((os.path.join(ROOT, 'art', 'Background', n + e) for e in ('.jpg', '.jpeg', '.png') if os.path.exists(os.path.join(ROOT, 'art', 'Background', n + e))), None)
        if not f: continue
        im = Image.open(f).convert('RGB').resize((SIZE * 2, SIZE * 2), Image.LANCZOS)
        im = seamless(im).resize((SIZE, SIZE), Image.LANCZOS)
        b = io.BytesIO(); im.save(b, 'JPEG', quality=86)
        out[n] = 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode()
        print(n, len(b.getvalue()) // 1024, 'KB')
    js = ['// generated by tools/tiles.py from art/Background — do not edit by hand', 'const TILES = {']
    js += [f"  {n}: '{src}'," for n, src in out.items()] + ['};']
    open(os.path.join(ROOT, 'js', 'ui', 'tiles.js'), 'w', encoding='utf-8').write('\n'.join(js) + '\n')

build()
