# Lists the radio voice files in Speak/ for the game: js/ui/voices.js (a browser can't list a folder by itself).
#   python tools/voices.py
# Speak/<Language>/<event>/<Voice>_<n>.mp3 — Language: English or Hebrew; event: one of EVENTS. The game plays any
# of an event's files at random (not the same one twice running).
import json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
EVENTS = ['selected', 'on_the_way', 'attacking', 'holding', 'retreating', 'in_position', 'under_attack', 'heavy_losses',
          'squad_lost', 'friendly_fire', 'promoted', 'say_again', 'forward_hq', 'building_lost',
          'base_attack', 'fhq_attack', 'hq_attack', 'drone_lost',
          'dozer_ready', 'dozer_idle', 'radio_ready', 'fhq_ready', 'drone_ready', 'place_hq', 'hq_ready',
          'took_radar', 'took_power', 'took_fuel', 'took_post', 'lost_post', 'can_build',
          'missile_incoming', 'intercepted']
AUDIO = ('.mp3', '.wav', '.ogg', '.m4a')

def build():
    out = {}
    base = os.path.join(ROOT, 'Speak')
    for lang in sorted(os.listdir(base)) if os.path.isdir(base) else []:
        for ev in EVENTS:
            d = os.path.join(base, lang, ev)
            if not os.path.isdir(d): continue
            files = [f for f in sorted(os.listdir(d)) if os.path.splitext(f)[1].lower() in AUDIO]
            if files: out.setdefault(lang, {})[ev] = [f'Speak/{lang}/{ev}/{f}' for f in files]
        unknown = [f for f in os.listdir(os.path.join(base, lang)) if f not in EVENTS]
        if unknown: print(f'  {lang}: not an event folder, skipped: {", ".join(unknown)}')
    js = '// generated by tools/voices.py from Speak/ — do not edit by hand\nconst VOICES = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n'
    open(os.path.join(ROOT, 'js', 'ui', 'voices.js'), 'w', encoding='utf-8').write(js)
    for lang, evs in out.items(): print(lang, ', '.join(f'{e} {len(f)}' for e, f in evs.items()))

if __name__ == '__main__': build()
